# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the project’s jar file to the container
COPY target/task-manager-1.0.0.jar task-manager.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "task-manager.jar"]
